


//===============================================================================================================================================================================
//=================================== PUEDE QUE LOS COLORES NO COMBINEN O NO TENGAN SENTIDO.. AUN NO ESTOY EN ESA FACE, PORFAVOR NO CAMBIAR COLORES! ============================
//===============================================================================================================================================================================


package vista;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pablo
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard_PROTOTIPO
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        padre = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        header1 = new javax.swing.JLabel();
        header2 = new javax.swing.JLabel();
        header3 = new javax.swing.JLabel();
        sidepanel = new javax.swing.JPanel();
        boton1 = new javax.swing.JPanel();
        boton_status = new javax.swing.JPanel();
        Texto_boton = new javax.swing.JLabel();
        boton2 = new javax.swing.JPanel();
        boton_status2 = new javax.swing.JPanel();
        Texto_boton2 = new javax.swing.JLabel();
        boton3 = new javax.swing.JPanel();
        boton_status3 = new javax.swing.JPanel();
        Texto_boton3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        padre.setBackground(new java.awt.Color(255, 255, 255));
        padre.setLayout(null);

        Header.setLayout(null);

        header1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Triangulos Oscuros.png"))); // NOI18N
        Header.add(header1);
        header1.setBounds(780, 0, 400, 90);

        header2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Triangulos Oscuros.png"))); // NOI18N
        Header.add(header2);
        header2.setBounds(0, 0, 400, 90);

        header3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Triangulos Oscuros.png"))); // NOI18N
        Header.add(header3);
        header3.setBounds(400, 0, 400, 90);

        padre.add(Header);
        Header.setBounds(0, 0, 1180, 90);

        sidepanel.setBackground(new java.awt.Color(51, 51, 51));
        sidepanel.setLayout(null);

        boton1.setBackground(new java.awt.Color(102, 102, 102));
        boton1.setLayout(null);

        boton_status.setBackground(new java.awt.Color(0, 204, 255));
        boton_status.setEnabled(false);
        boton_status.setOpaque(false);

        javax.swing.GroupLayout boton_statusLayout = new javax.swing.GroupLayout(boton_status);
        boton_status.setLayout(boton_statusLayout);
        boton_statusLayout.setHorizontalGroup(
            boton_statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        boton_statusLayout.setVerticalGroup(
            boton_statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        boton1.add(boton_status);
        boton_status.setBounds(0, 0, 10, 60);

        Texto_boton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Texto_boton.setForeground(new java.awt.Color(255, 255, 255));
        Texto_boton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_boton.setText("TEXTO1");
        Texto_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Texto_botonMousePressed(evt);
            }
        });
        boton1.add(Texto_boton);
        Texto_boton.setBounds(10, 0, 190, 60);

        sidepanel.add(boton1);
        boton1.setBounds(0, 120, 200, 60);

        boton2.setBackground(new java.awt.Color(102, 102, 102));
        boton2.setLayout(null);

        boton_status2.setBackground(new java.awt.Color(0, 204, 255));
        boton_status2.setEnabled(false);
        boton_status2.setOpaque(false);

        javax.swing.GroupLayout boton_status2Layout = new javax.swing.GroupLayout(boton_status2);
        boton_status2.setLayout(boton_status2Layout);
        boton_status2Layout.setHorizontalGroup(
            boton_status2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        boton_status2Layout.setVerticalGroup(
            boton_status2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        boton2.add(boton_status2);
        boton_status2.setBounds(0, 0, 10, 60);

        Texto_boton2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Texto_boton2.setForeground(new java.awt.Color(255, 255, 255));
        Texto_boton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_boton2.setText("TEXTO2");
        Texto_boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Texto_boton2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Texto_botonMousePressed(evt);
            }
        });
        boton2.add(Texto_boton2);
        Texto_boton2.setBounds(10, 0, 190, 60);

        sidepanel.add(boton2);
        boton2.setBounds(0, 190, 200, 60);

        boton3.setBackground(new java.awt.Color(102, 102, 102));
        boton3.setLayout(null);

        boton_status3.setBackground(new java.awt.Color(0, 204, 255));
        boton_status3.setEnabled(false);
        boton_status3.setOpaque(false);

        javax.swing.GroupLayout boton_status3Layout = new javax.swing.GroupLayout(boton_status3);
        boton_status3.setLayout(boton_status3Layout);
        boton_status3Layout.setHorizontalGroup(
            boton_status3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        boton_status3Layout.setVerticalGroup(
            boton_status3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        boton3.add(boton_status3);
        boton_status3.setBounds(0, 0, 10, 60);

        Texto_boton3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Texto_boton3.setForeground(new java.awt.Color(255, 255, 255));
        Texto_boton3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_boton3.setText("TEXTO3");
        Texto_boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Texto_botonMousePressed(evt);
            }
        });
        boton3.add(Texto_boton3);
        Texto_boton3.setBounds(10, 0, 190, 60);

        sidepanel.add(boton3);
        boton3.setBounds(0, 260, 200, 60);

        padre.add(sidepanel);
        sidepanel.setBounds(0, 80, 200, 720);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Triangulos Oscuros.png"))); // NOI18N
        padre.add(jLabel3);
        jLabel3.setBounds(400, 0, 400, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Triangulos Oscuros.png"))); // NOI18N
        padre.add(jLabel4);
        jLabel4.setBounds(400, 0, 400, 90);

        getContentPane().add(padre);
        padre.setBounds(0, 0, 1130, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Texto_botonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Texto_botonMousePressed
     
        Component frame = null;
        JOptionPane.showMessageDialog(frame, "Estas haciendo click en un boton");
        
        boolean Texto_botonMousePressed=true;
        resetColor(boton_status);
        while (Texto_botonMousePressed) {
            setColor(boton_status);
        }   
        
        
        
    }//GEN-LAST:event_Texto_botonMousePressed

    private void Texto_boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Texto_boton2MouseClicked
        
        boolean Texto_boton2MouseClicked = true;
        
        if (Texto_boton2MouseClicked(true)){
            
        }
        
        
    }//GEN-LAST:event_Texto_boton2MouseClicked

/////////////////////////////////////////////////////////////////////////////////

    // Esto pone y resetea el color a los indicadores!! 
    
    //encendido
    void setColor(JPanel panel){
        panel.setBackground(new Color(0,204,255));
    }
    //apagado
    void resetColor(JPanel panel){
       panel.setBackground(new Color(255,255,255));
    }
    
    
    // Fin de set and reset indicadores!
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Texto_boton;
    private javax.swing.JLabel Texto_boton2;
    private javax.swing.JLabel Texto_boton3;
    private javax.swing.JPanel boton1;
    private javax.swing.JPanel boton2;
    private javax.swing.JPanel boton3;
    private javax.swing.JPanel boton_status;
    private javax.swing.JPanel boton_status2;
    private javax.swing.JPanel boton_status3;
    private javax.swing.JLabel header1;
    private javax.swing.JLabel header2;
    private javax.swing.JLabel header3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel padre;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables

    private void setColor(JLabel Texto_boton) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
